name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout

      - uses: actions/setup-node
        with:
          node-version: "lts/krypton"

      - run: npm ci

      - run: npm test
